### PR TITLE
xmpp reconnect after WebSocket connection error

### PR DESCRIPTION
**Pull request by RDLemos**
Allow the XMPP Client to try to reconnect to the Server, if the
WebSocket connection gets disconnected. The client will try to
reconnect according to the default

### CODE REVIEW

**Review by RDLemos — COMMENTED** [review]
@guness : Any chance of this patch beeing reviewed and pushed in this week?

**Comment by guness** [comment]
reconnect was causing trouble, have you checked it?

**Comment by RDLemos** [comment]
What kind of trouble? I have checked on our server, and was working fine. Before the change, once we lost the WS connection, we would need to restart the server. After the change, when the WS is lost, the XMPP client will try to reconnect after the time-out set (10s).

**Comment by RDLemos** [comment]
These are the result of my testing using the reconnect option:
1) Using reconnect option, once we get a WS error detected on the connection (Network down), the xmpp client tries to re-establish the stream:
23:49:30.681Z ERROR appIMPServer:
    [FCM]: Socket error [Dev Server]: 
    { [Error: read ETIMEDOUT] code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'read' }                                                                                                     
                                                                                                                                                                                           
  xmpp:connection use lazy socket +3s
  xmpp:connection setup stream +1ms
  xmpp:connection use lazy socket +631ms
  xmpp:connection setup stream +1ms
  xmpp:connection use lazy socket +1s
  xmpp:connection setup stream +1ms
  xmpp:connection use lazy socket +2s
  xmpp:connection setup stream +1ms
  xmpp:connection use lazy socket +1s
  xmpp:connection setup stream +1ms
  xmpp:connection use lazy socket +2s
  xmpp:connection setup stream +0ms

2) Once I reestablish the server connection ( network Up), the CMPP-Client reconnects the WS, and reconnect the stream:

  xmpp:connection use lazy socket +24s
  xmpp:connection setup stream +1ms
  xmpp:connection send: <stream:stream xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams" version="1.0" to="gcm.googleapis.com"> +247ms
  xmpp:connection receive: <stream:stream from="gcm.googleapis.com" id="8D7C819307C259C1" version="1.0" xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client"> +129ms
  xmpp:connection receive: <stream:features><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>X-OAUTH2</mechanism><mechanism>X-GOOGLE-TOKEN</mechanism><mechanism>PLAIN</mechanism></mechanisms></stream:features> +1ms
  xmpp:connection send: <auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="PLAIN">MjgyMjE5MzA5NzI5QGdjbS5nb29nbGVhcGlzLmNvbQAyODIyMTkzMDk3MjkAQUl6YVN5Q0lGdkN1SU5ZS1Y3RzA4aFgxVVg0OXpXUnFCVFk0ekpn</auth> +1ms
  xmpp:connection receive: <success xmlns="urn:ietf:params:xml:ns:xmpp-sasl"/> +76ms
  xmpp:connection send: <stream:stream xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams" version="1.0" to="gcm.googleapis.com"> +0ms
  xmpp:connection receive: <stream:stream from="gcm.googleapis.com" id="36F472C27CAC4AFC" version="1.0" xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client"> +41ms
  xmpp:connection receive: <stream:features><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"/><session xmlns="urn:ietf:params:xml:ns:xmpp-session"/></stream:features> +1ms
  xmpp:connection send: <bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"><resource>96C5361B</resource></bind> +1ms
  xmpp:connection receive: <iq id="bind" type="result"><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"><jid>282219309729@gcm.googleapis.com/96C5361B</jid></bind></iq> +43ms
  xmpp:connection send: <session xmlns="urn:ietf:params:xml:ns:xmpp-session"/> +1ms
  xmpp:connection receive:   +1ms
  xmpp:connection receive: <iq from="gcm.googleapis.com" type="result" id="sess"/> +47ms
23:59:18.957Z  INFO appIMPServer: [FCM]: Connected to FCM for Prod Server notifications

@guness : What problem did you have with reconnect?

I am waiting for this update to be able to allow some of our server users to start using our push notifications service.

**Comment by RDLemos** [comment]
@guness : Do you think you will be able to update the npm to version 1.6 with this change today or tomorrow?

**Comment by guness** [comment]
published

**Pull request merged**
